"""
Merge request and release creation utilities for GitHub and GitLab.
"""

import subprocess
from pathlib import Path

from . import utils
from .gitlab_api import GitLabAPI


def create_github_pr(
    branch_name: str,
    version: str,
    changelog_preview: str,
    mr_target_branch: str,
    changelog_file: str,
    pyproject_file: str,
    tag_prefix: str = "v",
    mr_title_template: str = "Release {version}",
    dry_run: bool = False,
    logger=None,
) -> bool:
    """Create a GitHub Pull Request using gh CLI."""
    if dry_run:
        if logger:
            logger.log_info(
                f"DRY RUN: Would create GitHub PR for {branch_name} -> {mr_target_branch}"
            )
        return True

    try:
        # Check if gh CLI is available
        utils.run_command(["gh", "--version"])
    except subprocess.CalledProcessError:
        if logger:
            logger.log_error(
                "GitHub CLI (gh) not found. Please install it: https://cli.github.com/"
            )
        return False

    try:
        # Format title and description
        title = mr_title_template.format(version=f"{tag_prefix}{version}")

        # Generate description
        pyproject_update = (
            f"- Bump version in {pyproject_file} to {version}\n"
            if Path(pyproject_file).exists()
            else ""
        )
        description = f"""🚀 **Release {tag_prefix}{version}**

This pull request contains the changelog and version updates for release `{tag_prefix}{version}`.

## Changes included:
- Updated `{changelog_file}` with release notes
{pyproject_update}- Will create git tag `{tag_prefix}{version}` after merge

## Changelog Preview:
{changelog_preview}

---
*This PR was auto-generated by the release generator*
*Target branch: {mr_target_branch}*"""

        # Create PR using gh CLI
        cmd = [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            description,
            "--base",
            mr_target_branch,
            "--head",
            branch_name,
        ]

        _ = utils.run_command(cmd, capture_output=False)

        if logger:
            logger.log_success(
                f"Created GitHub PR: {branch_name} -> {mr_target_branch}"
            )
        return True

    except subprocess.CalledProcessError as e:
        if logger:
            logger.log_error(f"Failed to create GitHub PR: {e}")
        return False


def create_gitlab_mr(
    branch_name: str,
    version: str,
    changelog_preview: str,
    mr_target_branch: str,
    changelog_file: str,
    pyproject_file: str,
    gitlab_token: str,
    tag_prefix: str = "v",
    mr_title_template: str = "Release {version}",
    dry_run: bool = False,
    logger=None,
) -> bool:
    """Create a GitLab Merge Request using GitLab API."""
    if dry_run:
        if logger:
            logger.log_info(
                f"DRY RUN: Would create GitLab MR for {branch_name} -> {mr_target_branch}"
            )
        return True

    try:
        # Get remote URL
        remote_url = utils.get_remote_url()
        if not remote_url:
            if logger:
                logger.log_error("Could not determine remote URL")
            return False

        # Initialize GitLab API
        gitlab_api = GitLabAPI(remote_url, gitlab_token)

        # Format title and description
        title = mr_title_template.format(version=f"{tag_prefix}{version}")

        # Generate description
        pyproject_update = (
            f"- Bump version in {pyproject_file} to {version}\n"
            if Path(pyproject_file).exists()
            else ""
        )
        description = f"""🚀 **Release {tag_prefix}{version}**

This merge request contains the changelog and version updates for release `{tag_prefix}{version}`.

## Changes included:
- Updated `{changelog_file}` with release notes
{pyproject_update}- Will create git tag `{tag_prefix}{version}` after merge

## Changelog Preview:
{changelog_preview}

---
*This MR was auto-generated by the release generator*
*Target branch: {mr_target_branch}*"""

        # Create MR
        mr_response = gitlab_api.create_merge_request(
            source_branch=branch_name,
            target_branch=mr_target_branch,
            title=title,
            description=description,
        )

        if logger:
            mr_url = mr_response.get("web_url", "")
            logger.log_success(
                f"Created GitLab MR: {branch_name} -> {mr_target_branch}"
            )
            if mr_url:
                logger.log_info(f"MR URL: {mr_url}")

        return True

    except Exception as e:
        if logger:
            logger.log_error(f"Failed to create GitLab MR: {e}")
        return False


def create_gitlab_release(
    version: str,
    changelog: str,
    gitlab_token: str,
    tag_prefix: str = "v",
    dry_run: bool = False,
    logger=None,
) -> bool:
    """Create a GitLab release using GitLab API."""
    if dry_run:
        if logger:
            logger.log_info(
                f"DRY RUN: Would create GitLab release for {tag_prefix}{version}"
            )
        return True

    try:
        # Get remote URL
        remote_url = utils.get_remote_url()
        if not remote_url:
            if logger:
                logger.log_error("Could not determine remote URL")
            return False

        # Initialize GitLab API
        gitlab_api = GitLabAPI(remote_url, gitlab_token)

        # Create release
        tag_name = f"{tag_prefix}{version}"
        release_name = f"Release {tag_name}"

        # Clean up changelog for release description
        release_description = changelog.replace(
            f"# 📦 Release {tag_name} – ", ""
        ).strip()

        release_response = gitlab_api.create_release(
            tag_name=tag_name, name=release_name, description=release_description
        )

        if logger:
            release_url = release_response.get("_links", {}).get("self", "")
            logger.log_success(f"Created GitLab release: {release_name}")
            if release_url:
                logger.log_info(f"Release URL: {release_url}")

        return True

    except Exception as e:
        if logger:
            logger.log_error(f"Failed to create GitLab release: {e}")
        return False


def create_merge_request(
    branch_name: str,
    version: str,
    changelog_preview: str,
    mr_target_branch: str,
    changelog_file: str,
    pyproject_file: str,
    gitlab_token: str,
    tag_prefix: str = "v",
    mr_title_template: str = "Release {version}",
    dry_run: bool = False,
    logger=None,
) -> bool:
    """Create merge request based on remote type."""

    # Detect remote type
    remote_type = utils.get_remote_type()

    if remote_type == "github":
        return create_github_pr(
            branch_name,
            version,
            changelog_preview,
            mr_target_branch,
            changelog_file,
            pyproject_file,
            tag_prefix,
            mr_title_template,
            dry_run,
            logger,
        )
    elif remote_type == "gitlab":
        return create_gitlab_mr(
            branch_name,
            version,
            changelog_preview,
            mr_target_branch,
            changelog_file,
            pyproject_file,
            gitlab_token,
            tag_prefix,
            mr_title_template,
            dry_run,
            logger,
        )
    else:
        if logger:
            logger.log_error(f"Unsupported remote type: {remote_type}")
            logger.log_info("Supported types: github, gitlab")
        return False
