#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple

from releaser.drafter import utils

from ..console import bordered, console, create_duplicate_commits_table, logger
from .colors import Colors


class ReleaseGenerator:
    """Main class for generating releases with changelog and version updates."""

    def __init__(self):
        self.tag_prefix = "v"
        self.changelog_file = "CHANGELOG.md"
        self.pyproject_file = "pyproject.toml"
        self.date = datetime.now().strftime("%Y-%m-%d")
        self.dry_run = False
        self.mode = "auto"
        self.manual_version = ""
        self.create_mr = False
        self.mr_target_branch = ""
        self.check_duplicates = False
        self.auto_squash_duplicates = False
        self.auto_release = False
        self.gitlab_token = None
        self.no_interactive = False  # NEW: Skip all prompts
        self.force = False  # NEW: Ignore warnings
        self.mr_title_template = "Release {version}"
        self.mr_description_template = """🚀 **Release {version}**

This merge request contains the changelog and version updates for release `{version}`.

## Changes included:
- Updated `{changelog_file}` with release notes
{pyproject_update}- Will create git tag `{tag}` after merge

## Changelog Preview:
{changelog_preview}

---
*This MR was auto-generated by the release generator*
*Target branch: {target_branch}*"""

    def log_info(self, message: str):
        logger.info(message)

    def log_success(self, message: str):
        logger.success(message)

    def log_warning(self, message: str):
        logger.warning(message)

    def log_error(self, message: str):
        logger.error(message)

    def highlight_value(self, value: str) -> str:
        """Highlight important values in red."""
        return f"[bright_red bold]{value}[/bright_red bold]"

    def display_bordered_changelog(self, changelog: str):
        """Display changelog in a formatted table similar to duplicate commits."""
        title = "DRY RUN - CHANGELOG PREVIEW" if self.dry_run else "CHANGELOG PREVIEW"
        bordered.create_bordered_content(changelog, title, self.dry_run)

    def display_duplicate_commits_table(
        self, duplicates: Dict[str, List[Tuple[str, str]]]
    ):
        """Display duplicate commits in a formatted table."""
        if not duplicates:
            self.log_success("No duplicate commit messages found!")
            return

        table = create_duplicate_commits_table(duplicates)
        console.print(table)

        # Summary
        total_duplicates = sum(len(commits) for commits in duplicates.values())
        unique_messages = len(duplicates)
        console.print()
        self.log_warning(
            f"Found {total_duplicates} duplicate commits across {unique_messages} different messages"
        )

        if self.auto_squash_duplicates and not self.dry_run:
            self.log_info(
                "🔧 Auto-squash is enabled - these duplicates will be automatically squashed"
            )

    def auto_squash_duplicate_commits(
        self, duplicates: Dict[str, List[Tuple[str, str]]], since_tag: str = ""
    ) -> bool:
        """Automatically squash all duplicate commits."""
        if self.dry_run:
            self.log_info("DRY RUN: Would auto-squash all duplicate commits")
            return True

        if not duplicates:
            return True

        try:
            # Start interactive rebase
            cmd = ["git", "rebase", "-i"]
            if since_tag:
                cmd.append(f"{since_tag}..HEAD")
            else:
                # Get the number of commits to rebase
                result = utils.run_command(["git", "log", "--oneline", "--no-merges"])
                commit_count = (
                    len(result.stdout.strip().split("\n"))
                    if result.stdout.strip()
                    else 0
                )
                if commit_count > 0:
                    cmd.append(f"HEAD~{commit_count}")
                else:
                    self.log_warning("No commits found to rebase")
                    return False

            self.log_info("Starting automatic squash of duplicate commits...")

            # For each group of duplicates, we'll mark all but the first as "squash"
            # This is a simplified approach - in reality, git interactive rebase would need
            # a more sophisticated approach with a custom git sequence editor

            # Get all duplicate commit SHAs
            all_duplicate_shas = set()
            for commits in duplicates.values():
                for sha, _ in commits[1:]:  # Skip first commit in each group
                    all_duplicate_shas.add(sha[:7])  # Use short SHA

            self.log_info(f"Would squash {len(all_duplicate_shas)} duplicate commits")

            # Note: This is a simplified implementation. A full implementation would need
            # to modify the git rebase todo list to mark duplicates as "squash"
            # For now, we'll just log what would be done

            for message, commits in duplicates.items():
                self.log_info(f"Squashing duplicates for: {message[:50]}...")
                for sha, _ in commits[1:]:
                    self.log_info(f"  - Would squash {sha[:7]}")

            self.log_success("Auto-squash completed successfully")
            return True

        except subprocess.CalledProcessError as e:
            self.log_error(f"Failed to auto-squash duplicates: {e}")
            return False

    def interactive_squash_duplicates(
        self, duplicates: Dict[str, List[Tuple[str, str]]]
    ) -> bool:
        """Interactively choose which duplicate commits to squash."""
        if self.dry_run:
            self.log_info(
                "DRY RUN: Would interactively squash selected duplicate commits"
            )
            return True

        if not duplicates:
            return True

        print()
        self.log_info("Interactive squash mode - choose which duplicates to squash:")
        print()

        commits_to_squash = []

        for message, commits in duplicates.items():
            print(
                f"Duplicate message: {Colors.YELLOW}{message[:60]}...{Colors.NC}"
                if len(message) > 60
                else f"Duplicate message: {Colors.YELLOW}{message}{Colors.NC}"
            )
            print(f"Found {len(commits)} copies:")

            for i, (sha, _) in enumerate(commits):
                print(
                    f"  {i + 1}. {sha[:7]} ({'keep as-is' if i == 0 else 'squash candidate'})"
                )

            print()
            while True:
                choice = (
                    input(f"Squash commits for this message? (y/n/s=skip): ")
                    .strip()
                    .lower()
                )
                if choice in ["y", "yes"]:
                    # Add all but the first commit to squash list
                    commits_to_squash.extend([sha for sha, _ in commits[1:]])
                    print(f"  ✓ Will squash {len(commits) - 1} commits")
                    break
                elif choice in ["n", "no"]:
                    print("  ✗ Keeping all commits as-is")
                    break
                elif choice in ["s", "skip"]:
                    print("  ⏭ Skipping this group")
                    break
                else:
                    print("Please enter 'y' (yes), 'n' (no), or 's' (skip)")
            print()

        if not commits_to_squash:
            self.log_info("No commits selected for squashing")
            return True

        # Show summary
        print(f"Summary: Will squash {len(commits_to_squash)} commits:")
        for sha in commits_to_squash:
            print(f"  - {sha[:7]}")
        print()

        confirm = input("Proceed with squashing these commits? (y/N): ").strip().lower()
        if confirm != "y":
            self.log_info("Interactive squash cancelled")
            return False

        try:
            # This is where the actual git rebase logic would go
            # For now, we'll simulate the process
            self.log_info("Starting interactive squash...")

            for sha in commits_to_squash:
                self.log_info(f"Squashing commit {sha[:7]}...")

            self.log_success("Interactive squash completed successfully")
            return True

        except Exception as e:
            self.log_error(f"Failed to perform interactive squash: {e}")
            return False

    def create_release_branch(self, version: str, base_branch: str) -> str:
        """Create and checkout a new release branch from the specified base branch."""
        from .git_operations import \
            create_release_branch as _create_release_branch

        return _create_release_branch(
            version, base_branch, self.tag_prefix, self.dry_run, self
        )

    def commit_release_changes(self, version: str) -> bool:
        """Commit the changelog and version changes."""
        from .git_operations import \
            commit_release_changes as _commit_release_changes

        return _commit_release_changes(
            version,
            self.changelog_file,
            self.pyproject_file,
            self.tag_prefix,
            self.dry_run,
            self,
        )

    def push_release_branch(self, branch_name: str) -> bool:
        """Push the release branch to remote."""
        from .git_operations import push_release_branch as _push_release_branch

        return _push_release_branch(branch_name, self.dry_run, self)

    def create_git_tag(self, version: str) -> bool:
        """Create git tag."""
        from .git_operations import create_git_tag as _create_git_tag

        return _create_git_tag(version, self.tag_prefix, self.dry_run, self)

    def push_git_tag(self, version: str) -> bool:
        """Push git tag to remote."""
        from .git_operations import push_git_tag as _push_git_tag

        return _push_git_tag(version, self.tag_prefix, self.dry_run, self)

    def create_github_pr(
        self, branch_name: str, version: str, changelog_preview: str
    ) -> bool:
        """Create a GitHub Pull Request using gh CLI."""
        from .mr_release import create_github_pr as _create_github_pr

        return _create_github_pr(
            branch_name,
            version,
            changelog_preview,
            self.mr_target_branch,
            self.changelog_file,
            self.pyproject_file,
            self.tag_prefix,
            self.mr_title_template,
            self.dry_run,
            self,
        )

    def create_gitlab_mr(
        self, branch_name: str, version: str, changelog_preview: str
    ) -> bool:
        """Create a GitLab Merge Request using GitLab API."""
        from .mr_release import create_gitlab_mr as _create_gitlab_mr

        return _create_gitlab_mr(
            branch_name,
            version,
            changelog_preview,
            self.mr_target_branch,
            self.changelog_file,
            self.pyproject_file,
            self.gitlab_token,
            self.tag_prefix,
            self.mr_title_template,
            self.dry_run,
            self,
        )

    def create_gitlab_release(self, version: str, changelog: str) -> bool:
        """Create a GitLab release using GitLab API."""
        from .mr_release import create_gitlab_release as _create_gitlab_release

        return _create_gitlab_release(
            version, changelog, self.gitlab_token, self.tag_prefix, self.dry_run, self
        )

    def create_merge_request(
        self, branch_name: str, version: str, changelog_preview: str
    ) -> bool:
        """Create merge request based on remote type."""
        from .mr_release import create_merge_request as _create_merge_request

        return _create_merge_request(
            branch_name,
            version,
            changelog_preview,
            self.mr_target_branch,
            self.changelog_file,
            self.pyproject_file,
            self.gitlab_token,
            self.tag_prefix,
            self.mr_title_template,
            self.dry_run,
            self,
        )

    def get_latest_tag(self) -> str:
        """Get the latest git tag, preferring remote tags."""
        return utils.get_latest_tag()

    def get_pyproject_version(self) -> str:
        """Get version from pyproject.toml."""
        return utils.get_pyproject_version(self.pyproject_file)

    def get_current_version(self) -> str:
        """Get the latest version from git tags or pyproject.toml."""
        from .changelog import get_current_version as _get_current_version

        return _get_current_version(self.tag_prefix, self.pyproject_file, self)

    def get_commits_since_tag(self, tag: str) -> List[str]:
        """Get commits since the last tag."""
        return utils.get_commits_since_tag(tag)

    def get_contributors(self, tag: str) -> str:
        """Get all contributors since last tag."""
        return utils.get_contributors(tag)

    def get_repo_url(self) -> str:
        """Get repository URL for comparison links."""
        return utils.get_repo_url()

    def parse_commit_type(self, commit: str) -> str:
        """Parse commit type from conventional commit format."""
        return utils.parse_commit_type(commit)

    def extract_pr_number(self, message: str) -> str:
        """Extract PR number from commit message."""
        return utils.extract_pr_number(message)

    def categorize_commits(self, commits: List[str]) -> str:
        """Categorize commits with template format."""
        from .changelog import categorize_commits as _categorize_commits

        return _categorize_commits(commits)

    def determine_version_bump(self, commits: List[str]) -> str:
        """Determine version bump type."""
        return utils.determine_version_bump(commits)

    def bump_version(self, current_version: str, bump_type: str) -> str:
        """Bump version based on type."""
        return utils.bump_version(current_version, bump_type, self.tag_prefix)

    def update_pyproject_version(self, new_version: str) -> bool:
        """Update pyproject.toml version."""
        from .changelog import \
            update_pyproject_version as _update_pyproject_version

        return _update_pyproject_version(
            self.pyproject_file, new_version, self.dry_run, self
        )

    def update_changelog(self, new_changelog: str) -> bool:
        """Update changelog with new template."""
        from .changelog import update_changelog as _update_changelog

        return _update_changelog(self.changelog_file, new_changelog, self.dry_run, self)

    def prompt_manual_version(self):
        """Prompt for manual version input."""
        from .changelog import prompt_manual_version as _prompt_manual_version

        self.manual_version = _prompt_manual_version()
        self.log_success(
            f"Using manual version: {self.highlight_value(self.tag_prefix + self.manual_version)}"
        )

    def prompt_release_notes(self) -> str:
        """Prompt for release notes input."""
        print()
        self.log_info("📝 Please provide release notes for this release:")
        print("  (Enter multiple lines, press Enter twice to finish)")
        print()
        
        lines = []
        empty_line_count = 0
        
        while True:
            line = input()
            if line.strip() == '':
                empty_line_count += 1
                if empty_line_count >= 2:
                    # Remove the last empty line that was added
                    if lines and lines[-1] == '':
                        lines.pop()
                    break
                lines.append(line)
            else:
                empty_line_count = 0
                lines.append(line)
        
        release_notes = '\n'.join(lines).strip()
        
        if release_notes:
            self.log_success("✅ Release notes captured")
        else:
            self.log_warning("⚠️  No release notes provided")
            
        return release_notes

    def is_git_repository(self) -> bool:
        """Check if we're in a git repository."""
        return utils.is_git_repository()

    def has_uncommitted_changes(self) -> bool:
        """Check for uncommitted changes."""
        return utils.has_uncommitted_changes()

    def display_git_workflow_visualization(
        self, new_version: str, release_branch: str = ""
    ):
        """Display a visual representation of the git workflow in dry-run mode."""
        from .visualization import \
            display_git_workflow_visualization as _display_workflow

        _display_workflow(
            new_version,
            release_branch,
            self.create_mr,
            self.auto_release,
            self.mr_target_branch,
            self.changelog_file,
            self.pyproject_file,
            self.tag_prefix,
            self.dry_run,
        )

    def main(self):
        """Main function."""
        mode_text = f"{self.mode} mode"
        if self.create_mr:
            mode_text += " with MR creation"
        if self.auto_release:
            mode_text += " and auto-release"
        if self.no_interactive:  # NEW: Show fully automated mode
            mode_text += " (fully automated)"

        self.log_info(f"🚀 Generating release in {mode_text}...")
        print()

        if not self.is_git_repository():
            self.log_error("Not in a git repository")
            sys.exit(1)

        # Check if current branch is allowed for release
        current_branch = utils.get_current_branch()
        allowed_branches = ['main']
        is_allowed = (
            current_branch in allowed_branches or
            current_branch.startswith('release/') or
            current_branch.startswith('hotfix/')
        )
        
        if not is_allowed:
            self.log_error(
                f"Release drafts can only be created from main, release/* or hotfix/* branches.\n"
                f"       Current branch: {self.highlight_value(current_branch)}"
            )
            sys.exit(1)

        # MODIFIED: Handle uncommitted changes in automated mode
        if self.has_uncommitted_changes():
            if self.no_interactive:
                if self.force:
                    self.log_warning(
                        "Uncommitted changes detected - continuing due to --force flag"
                    )
                else:
                    self.log_error(
                        "Uncommitted changes detected. Use --force to proceed in automated mode"
                    )
                    sys.exit(1)
            else:
                self.log_warning(
                    "You have uncommitted changes. Consider committing them first."
                )
                print()

        # Check for GitLab token if needed
        if (
            self.create_mr or self.auto_release
        ) and utils.get_remote_type() == "gitlab":
            if not self.gitlab_token and not os.getenv("GITLAB_TOKEN"):
                self.log_error(
                    "GitLab token not found. Set GITLAB_TOKEN environment variable or use --gitlab-token"
                )
                sys.exit(1)

        # Store original branch for potential restoration
        original_branch = utils.get_current_branch()
        self.log_info(f"Current branch: {self.highlight_value(original_branch)}")

        # MODIFIED: Handle duplicate commits automatically in no-interactive mode
        if self.check_duplicates:
            self.log_info("🔍 Checking for duplicate commit messages...")
            duplicates = utils.check_duplicate_commits(self.get_latest_tag())
            self.display_duplicate_commits_table(duplicates)

            if duplicates:
                if self.no_interactive:
                    # Automated mode - handle based on settings
                    if self.auto_squash_duplicates:
                        self.log_info(
                            "🤖 Automated mode: Auto-squashing duplicate commits"
                        )
                        if not self.auto_squash_duplicate_commits(
                            duplicates, self.get_latest_tag()
                        ):
                            if self.force:
                                self.log_warning(
                                    "Failed to auto-squash duplicates - continuing due to --force flag"
                                )
                            else:
                                self.log_error(
                                    "Failed to auto-squash duplicates in automated mode. Use --force to continue anyway"
                                )
                                sys.exit(1)
                    else:
                        self.log_info(
                            "🤖 Automated mode: Ignoring duplicate commits (auto-squash not enabled)"
                        )
                elif self.auto_squash_duplicates:
                    # Auto-squash mode
                    if self.auto_squash_duplicate_commits(
                        duplicates, self.get_latest_tag()
                    ):
                        self.log_success(
                            "Duplicate commits have been squashed automatically "
                        )
                        # Refresh commits list after squashing
                        commits = self.get_commits_since_tag(self.get_latest_tag())
                        commit_count = len([c for c in commits if c.strip()])
                        self.log_info(
                            f"Updated commit count: {self.highlight_value(str(commit_count))}"
                        )
                    else:
                        self.log_error("Failed to auto-squash duplicates")
                        response = (
                            input(
                                "Continue with release despite failed squash? (y/N): "
                            )
                            .strip()
                            .lower()
                        )
                        if response != "y":
                            self.log_warning("Release cancelled due to failed squash")
                            sys.exit(0)
                else:
                    # Interactive mode - ask user what to do
                    print()
                    print("Options:")
                    print("1. Continue with release (ignore duplicates)")
                    print("2. Auto-squash all duplicates")
                    print("3. Interactive squash (choose which to squash)")
                    print("4. Cancel release")

                    while True:
                        choice = input("Choose option (1-4): ").strip()
                        if choice == "1":
                            break
                        elif choice == "2":
                            if self.auto_squash_duplicate_commits(
                                duplicates, self.get_latest_tag()
                            ):
                                self.log_success(
                                    "✅ Duplicate commits have been squashed"
                                )
                                # Refresh commits list after squashing
                                commits = self.get_commits_since_tag(
                                    self.get_latest_tag()
                                )
                                commit_count = len([c for c in commits if c.strip()])
                                self.log_info(
                                    f"Updated commit count: {self.highlight_value(str(commit_count))}"
                                )
                            else:
                                self.log_error("Failed to squash duplicates")
                                continue
                            break
                        elif choice == "3":
                            if self.interactive_squash_duplicates(duplicates):
                                # Refresh commits list after squashing
                                commits = self.get_commits_since_tag(
                                    self.get_latest_tag()
                                )
                                commit_count = len([c for c in commits if c.strip()])
                                self.log_info(
                                    f"Updated commit count: {self.highlight_value(str(commit_count))}"
                                )
                            break
                        elif choice == "4":
                            self.log_warning("Release cancelled by user")
                            sys.exit(0)
                        else:
                            print("Please enter a number between 1-4")
                    print()

        # Determine target branch for MR
        if self.create_mr:
            if not self.mr_target_branch:  # Default to current branch
                self.mr_target_branch = original_branch
                self.log_info(
                    f"MR will target current branch: {self.highlight_value(self.mr_target_branch)}"
                )
            else:
                self.log_info(
                    f"MR will target specified branch: {self.highlight_value(self.mr_target_branch)}"
                )

        # Get current state
        latest_tag = ""
        new_version = ""
        release_branch = ""

        if self.mode == "auto":
            latest_tag = self.get_current_version()
            self.log_info(
                f"Auto mode: Latest tag from git: {self.highlight_value(latest_tag) if latest_tag else 'none'}"
            )
        else:
            latest_tag = self.get_latest_tag()
            if not self.no_interactive:  # Skip prompt in automated mode
                self.prompt_manual_version()
                new_version = self.manual_version
            else:
                self.log_error("Manual mode cannot be used with --no-interactive")
                sys.exit(1)

        commits = self.get_commits_since_tag(self.get_latest_tag())

        if not commits or (len(commits) == 1 and not commits[0].strip()):
            self.log_warning("No new commits found since last release")
            sys.exit(0)

        commit_count = len([c for c in commits if c.strip()])
        self.log_info(
            f"Found {self.highlight_value(str(commit_count))} commits since {self.highlight_value(latest_tag) if latest_tag else 'beginning'}"
        )

        # Process commits and determine version
        if self.mode == "auto":
            version_bump = self.determine_version_bump(commits)
            new_version = self.bump_version(latest_tag, version_bump)
            self.log_info(
                f"Auto-determined version bump: {self.highlight_value(version_bump)}"
            )

        changelog = self.categorize_commits(commits)
        contributors = self.get_contributors(self.get_latest_tag())
        repo_url = self.get_repo_url()
        previous_tag = self.get_latest_tag()

        print()
        self.log_info(
            f"Current version: {self.highlight_value(latest_tag) if latest_tag else 'none'}"
        )
        self.log_info(
            f"New version: {self.highlight_value(self.tag_prefix + new_version)}"
        )
        print()

        # Prompt for release notes if not in no-interactive mode
        release_notes = ""
        if not self.no_interactive and not self.dry_run:
            release_notes = self.prompt_release_notes()

        # Generate full changelog entry
        full_changelog = f"## 📦 Release {self.tag_prefix}{new_version} – {self.date}\n\n---\n"
        
        # Add release notes if provided
        if release_notes:
            full_changelog += f"\n### 📋 Release Notes\n\n{release_notes}\n\n---\n"
        
        full_changelog += f"\n{changelog}"

        # Add footer with contributors and comparison link
        if contributors:
            full_changelog += f"---\n\n**Contributors:** {contributors}"

        if repo_url and previous_tag:
            full_changelog += f"\n**Compare changes:** [{previous_tag}...{self.tag_prefix}{new_version}]({repo_url}/-/compare/{previous_tag}...{self.tag_prefix}{new_version})"

        full_changelog += "\n\n"

        # Display changelog with border (skip in no-interactive mode for cleaner output)
        if not self.no_interactive:
            self.display_bordered_changelog(full_changelog)

        # MODIFIED: Skip confirmation prompt in no-interactive mode
        if not self.dry_run and not self.no_interactive:
            action_text = (
                "create MR and proceed with release"
                if self.create_mr
                else "proceed with release"
            )
            response = input(f"{action_text}? (y/N): ").strip().lower()
            if response != "y":
                self.log_warning("Release cancelled")
                sys.exit(0)
        elif self.no_interactive and not self.dry_run:
            action_text = (
                "Creating MR and proceeding with release"
                if self.create_mr
                else "Proceeding with release"
            )
            self.log_info(f"🤖 Automated mode: {action_text}")

        # Create release branch if MR creation is enabled
        if self.create_mr:
            release_branch = self.create_release_branch(
                new_version, self.mr_target_branch
            )
            if not release_branch and not self.dry_run:
                self.log_error("Failed to create release branch")
                sys.exit(1)

        # Update files
        self.update_changelog(full_changelog)
        self.log_success(f"Updated {self.changelog_file}")

        # Update pyproject.toml if it exists
        if Path(self.pyproject_file).exists():
            self.update_pyproject_version(new_version)
        else:
            self.log_info(
                f"No {self.pyproject_file} found, skipping version update in Python project file"
            )

        # Create tag if not in MR mode (tag will be created after MR is merged)
        if not self.create_mr:
            # Commit the release changes before creating tag
            if not self.dry_run:
                if not self.commit_release_changes(new_version):
                    self.log_error("Failed to commit release changes")
                    sys.exit(1)
            else:
                self.log_info(
                    f"DRY RUN: Would commit release changes with message: 'chore: bump version to {self.tag_prefix}{new_version}'"
                )

            # Push the commit to remote before creating tag
            if not self.dry_run:
                try:
                    # Try to push, and if it fails due to no upstream, set upstream and push
                    current_branch = utils.get_current_branch()
                    try:
                        utils.run_command(["git", "push"], capture_output=False)
                    except subprocess.CalledProcessError:
                        # If push fails, try setting upstream
                        self.log_info(f"Setting upstream for branch {current_branch}")
                        utils.run_command(
                            ["git", "push", "--set-upstream", "origin", current_branch],
                            capture_output=False
                        )
                    self.log_success("Pushed release commit to remote")
                except subprocess.CalledProcessError as e:
                    self.log_error(f"Failed to push release commit: {e}")
                    sys.exit(1)
            else:
                self.log_info("DRY RUN: Would push release commit to remote")

            if self.create_git_tag(new_version):
                if self.push_git_tag(new_version):
                    # Create GitLab release if auto-release is enabled
                    if self.auto_release and utils.get_remote_type() == "gitlab":
                        self.create_gitlab_release(new_version, full_changelog)

                    print()
                    self.log_success("🎉 Release completed successfully!")

                    # NEW: Show release summary in automated mode
                    if self.no_interactive:
                        latest_tag = f"{self.tag_prefix}{new_version}"
                        repo_url = self.get_repo_url()
                        print()
                        print("📋 Release Summary:")
                        print(f"   ✅ Version: {latest_tag}")
                        print(f"   ✅ Tag created and pushed")
                        if self.auto_release and utils.get_remote_type() == "gitlab":
                            print(f"   ✅ GitLab release created")
                        print(f"   ✅ {self.changelog_file} updated")
                        if Path(self.pyproject_file).exists():
                            print(f"   ✅ {self.pyproject_file} updated")
                        print()
                        if repo_url:
                            print("🔗 Quick Links:")
                            if utils.get_remote_type() == "gitlab":
                                print(
                                    f"   📦 Release: {repo_url}/-/releases/{latest_tag}"
                                )
                            print(
                                f"   📝 Changelog: {repo_url}/-/blob/{latest_tag}/{self.changelog_file}"
                            )
                            if previous_tag:
                                print(
                                    f"   🔍 Compare: {repo_url}/-/compare/{previous_tag}...{latest_tag}"
                                )
                        print()
                        self.log_success(f"🚀 Release {latest_tag} is now live!")
        else:
            # Commit and push changes, then create MR
            if self.commit_release_changes(new_version):
                if self.push_release_branch(release_branch):
                    if self.create_merge_request(
                        release_branch, new_version, changelog
                    ):
                        print()
                        self.log_success("🎉 Release MR created successfully!")

                        # MODIFIED: If auto-release is enabled, continue with tag creation and release
                        if self.auto_release:
                            print()
                            self.log_info(
                                "🤖 Auto-release enabled: Continuing with tag creation and release..."
                            )

                            # Switch back to target branch for tagging
                            try:
                                utils.run_command(
                                    ["git", "checkout", self.mr_target_branch],
                                    capture_output=False,
                                )
                                self.log_info(
                                    f"Switched back to target branch: {self.highlight_value(self.mr_target_branch)}"
                                )
                            except subprocess.CalledProcessError as e:
                                self.log_error(
                                    f"Failed to switch to target branch: {e}"
                                )
                                return

                            # Create and push tag
                            if self.create_git_tag(new_version):
                                if self.push_git_tag(new_version):
                                    # Create GitLab release if it's a GitLab repo
                                    if utils.get_remote_type() == "gitlab":
                                        if self.create_gitlab_release(
                                            new_version, full_changelog
                                        ):
                                            print()
                                            self.log_success(
                                                "🎉 Complete auto-release finished successfully!"
                                            )

                                            # Show comprehensive release summary
                                            if self.no_interactive:
                                                latest_tag = (
                                                    f"{self.tag_prefix}{new_version}"
                                                )
                                                repo_url = self.get_repo_url()
                                                print()
                                                print("📋 Complete Release Summary:")
                                                print(
                                                    f"   ✅ Release branch: {release_branch}"
                                                )
                                                print(f"   ✅ Merge request created")
                                                print(f"   ✅ Version: {latest_tag}")
                                                print(f"   ✅ Tag created and pushed")
                                                print(f"   ✅ GitLab release created")
                                                print(
                                                    f"   ✅ {self.changelog_file} updated"
                                                )
                                                if Path(self.pyproject_file).exists():
                                                    print(
                                                        f"   ✅ {self.pyproject_file} updated"
                                                    )
                                                print()
                                                if repo_url:
                                                    print("🔗 Quick Links:")
                                                    print(
                                                        f"   📦 Release: {repo_url}/-/releases/{latest_tag}"
                                                    )
                                                    print(
                                                        f"   📝 Changelog: {repo_url}/-/blob/{latest_tag}/{self.changelog_file}"
                                                    )
                                                    if previous_tag:
                                                        print(
                                                            f"   🔍 Compare: {repo_url}/-/compare/{previous_tag}...{latest_tag}"
                                                        )
                                                print()
                                                self.log_success(
                                                    f"🚀 Release {latest_tag} is now live!"
                                                )
                                            return
                                        else:
                                            self.log_warning(
                                                "Tag created but GitLab release creation failed"
                                            )
                                    else:
                                        print()
                                        self.log_success(
                                            "🎉 Auto-release completed (tag created and pushed)!"
                                        )
                                        self.log_info(
                                            "Note: GitLab release creation is only available for GitLab repositories"
                                        )
                                        return
                                else:
                                    self.log_error(
                                        "Failed to push tag - auto-release incomplete"
                                    )
                                    return
                            else:
                                self.log_error(
                                    "Failed to create tag - auto-release incomplete"
                                )
                                return
                        else:
                            # Original behavior for non-auto-release MR mode
                            print()
                            if (
                                not self.no_interactive
                            ):  # Only show next steps in interactive mode
                                print("Next steps:")
                                print(
                                    f"- Review the MR for release {self.highlight_value(self.tag_prefix + new_version)}"
                                )
                                print("- Merge the MR when ready")
                                tag_and_release_cmd = f"git tag -a {self.tag_prefix + new_version} -m 'Release {self.tag_prefix}{new_version}' && git push origin {self.tag_prefix + new_version}"
                                print(
                                    f"- After merging, create and push the tag: {self.highlight_value(tag_and_release_cmd)}"
                                )
                                print("- Create a GitHub/GitLab release if needed")
                        return
                    else:
                        self.log_warning("MR creation failed, but branch was pushed")
                        if not self.no_interactive:
                            print()
                            print("You can manually create the MR:")
                            print(
                                f"- Source branch: {self.highlight_value(release_branch)}"
                            )
                            print(
                                f"- Target branch: {self.highlight_value(self.mr_target_branch)}"
                            )
                            print(
                                f"- Title: Release {self.highlight_value(self.tag_prefix + new_version)}"
                            )
                else:
                    self.log_error("Failed to push release branch")
                    return
            else:
                self.log_error("Failed to commit release changes")
                return

        # Show next steps only in interactive mode
        if not self.no_interactive and not self.create_mr:
            print()
            print("Next steps:")
            print(f"- Review the changelog in {self.changelog_file}")
            if Path(self.pyproject_file).exists():
                print(f"- Review the version update in {self.pyproject_file}")
            if not self.dry_run:
                print(
                    f"- Commit the changes: git add . && git commit -m 'Release {self.highlight_value(self.tag_prefix + new_version)}'"
                )
                print(
                    f"- Push the tag: git push origin {self.highlight_value(self.tag_prefix + new_version)}"
                )
                if not self.auto_release:
                    print("- Create a release on GitHub/GitLab if needed")


def main():
    parser = argparse.ArgumentParser(
        description="Local Release Generator with GitLab API Integration"
    )

    # Boolean flags (True/False)
    parser.add_argument(
        "-n",
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be generated without making changes",
    )
    parser.add_argument(
        "--manual",
        action="store_true",
        default=False,
        help="Manually specify version (default: auto-determine from git tags)",
    )
    parser.add_argument(
        "-r",
        "--create-mr",
        action="store_true",
        default=False,
        help="Create a new branch and merge request with the release changes",
    )
    parser.add_argument(
        "-d",
        "--check-commit-duplicates",
        action="store_true",
        default=False,
        help="Check for duplicate commit messages and display them in a table",
    )
    parser.add_argument(
        "-s",
        "--squash-commit-duplicates",
        action="store_true",
        default=False,
        help="Automatically squash duplicate commits (requires --check-commit-duplicates)",
    )
    # MODIFIED: Updated help text for auto-release to indicate it includes MR creation
    parser.add_argument(
        "-a",
        "--auto-release",
        action="store_true",
        default=False,
        help="Automatically create release branch, MR, and GitLab release (includes --create-mr functionality)",
    )

    # NEW: Automated mode flags
    parser.add_argument(
        "--no-interactive",
        action="store_true",
        default=False,
        help="Run in fully automated mode without any prompts or confirmations",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        default=False,
        help="Force execution even with warnings (uncommitted changes, failed squash, etc.)",
    )

    # String arguments
    parser.add_argument(
        "-t",
        "--target",
        type=str,
        default="",
        help="Target branch for the merge request (default: current branch)",
    )
    parser.add_argument(
        "--gitlab-token",
        type=str,
        default="",
        help="GitLab API token (can also be set via GITLAB_TOKEN environment variable)",
    )

    args = parser.parse_args()

    generator = ReleaseGenerator()
    generator.dry_run = args.dry_run
    generator.mode = "manual" if args.manual else "auto"
    generator.create_mr = args.create_mr
    generator.check_duplicates = args.check_commit_duplicates
    generator.auto_squash_duplicates = args.squash_commit_duplicates
    generator.auto_release = args.auto_release
    generator.gitlab_token = args.gitlab_token or os.getenv("GITLAB_TOKEN")

    # NEW: Set automated mode flags
    generator.no_interactive = args.no_interactive
    generator.force = args.force

    # MODIFIED: Auto-release now automatically enables create-mr
    if args.auto_release:
        generator.create_mr = True
        generator.log_info(
            "🤖 Auto-release enabled - automatically including MR creation"
        )

    # Validate squash requires check-dups
    if args.squash_commit_duplicates and not args.check_commit_duplicates:
        generator.log_error(
            "--squash-commit-duplicates requires --check-commit-duplicates"
        )
        sys.exit(1)

    # NEW: Validate no-interactive mode constraints
    if args.no_interactive:
        generator.log_info("🤖 Fully automated mode enabled - no prompts will be shown")

        # Manual mode cannot be used with no-interactive
        if args.manual:
            generator.log_error(
                "Manual mode (--manual) cannot be used with --no-interactive"
            )
            sys.exit(1)

        # MODIFIED: In automated mode, we should enable auto-release by default if not already set
        if not generator.auto_release and not args.create_mr:
            generator.log_info(
                "🤖 Automated mode: Enabling auto-release (includes MR creation)"
            )
            generator.auto_release = True
            generator.create_mr = True

    # Handle MR target branch logic
    if (
        generator.create_mr
    ):  # MODIFIED: Check generator.create_mr instead of args.create_mr
        if args.target:
            generator.mr_target_branch = args.target
        else:
            # Will be set to current branch in main() method
            generator.mr_target_branch = ""

    # Status messages
    if args.dry_run:
        generator.log_info("🧪 Dry run mode - no changes will be made")

    if args.manual:
        generator.log_info("🔧 Mode set to: manual")

    if generator.create_mr:  # MODIFIED: Check generator.create_mr
        target_info = "current branch" if not args.target else args.target
        generator.log_info(
            f"🔀 MR mode enabled - will create branch and MR targeting {target_info}"
        )

    if args.check_commit_duplicates:
        generator.log_info("🔍 Duplicate commit checking enabled")
        if args.squash_commit_duplicates:
            generator.log_info("🔧 Auto-squash duplicates enabled")

    if args.auto_release:
        generator.log_info("🚀 Auto-release enabled for GitLab (includes MR creation)")

    if args.force:
        generator.log_info("💪 Force mode enabled - ignoring warnings")

    generator.main()


if __name__ == "__main__":
    main()
